### ISSUE TITLE
harmonic_oscillator.py stability

### ISSUE THREAD

**Issue by danbri** [dwd31415/tensorflow-diff-eq#2]
Am I wrong in expecting this to oscillate in a stable repeating fashion indefinitely? However when I run it I'm seeing the oscillations gradually get larger and larger. Feel like I'm missing something obvious, thanks for any pointers...

**Comment by dwd31415** [comment]
This would indeed be the analytic solution. However in this numerical simulation there is a simulation error term, which grows over time, in this case this leads to the amplitude of the oscillations gradually increasing.

**Comment by danbri** [comment]
Thanks for the explanation!
